<?php
 $config = Zend_Registry::get('config');
 $db = Zend_Registry::get('db');
 $request = Zend_Controller_Front::getInstance()->getRequest();
?>

<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <base href="<?= $config->baseurl; ?>" />
    <title>Het Vragenboekje</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- Le styles -->
    <link href="assets/css/reset.css" rel="stylesheet">
    <link href="assets/css/main.css" rel="stylesheet">

    <!-- Le fonts -->
    <link href='http://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>

    <!-- Le bootstrap -->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.placeholder.min.js"></script>

  </head>

  <body>

    <div class="top">

        <div class="centered">

            <div class="logo">&nbsp;</div>

        </div>

    </div>

    <div class="menu">

        <div class="centered">

            <ul>

                <li <?php if($request->controller == 'page') echo 'class="active"'; ?>><a href="">Home</a></li>
                <li <?php if($request->controller == 'categorieen') echo 'class="active"'; ?>><a href="categorieen">Categorieën</a></li>
                <li <?php if($request->controller == 'search') echo 'class="active"'; ?>><a href="zoeken">Zoeken</a></li>
                <?php if(isset($_SESSION['user'])): ?><li <?php if($request->action == 'overview') echo 'class="active"'; ?>><a href="questions">Mijn vragen</a></li><?php endif; ?>
                
                <!-- SUBMENU
                <?php if(isset($_SESSION['user'])): ?><li <?php if($request->controller == 'ask') echo 'class="active"'; ?>><a href="steleenvraag">Stel een vraag</a></li><?php endif; ?>
                <?php if(isset($_SESSION['user'])): ?><li <?php if($request->controller == 'profile') echo 'class="active"'; ?>><a href="profiel">Bewerk profiel</a></li><?php endif; ?>
                -->
            
            </ul>

        </div>

    </div>

    <hr class="shadow-border-menu" />

    <div class="container">

        <div class="content clearfix">

              <div class="content-left">

                    <div class="search">

                        <div class="search-img">&nbsp;</div>

                        <div class="search-box">

                            <p>De leukste vragensite van Nederland met mogelijheden tot printen op A5 formaat!</p>

                            <form action="zoeken" method="POST">

                                <div class="search-bar">

                                    <input type="text" name="s" placeholder="Zoek op vragen.." />
                                    <input type="submit" class="submit hidden" />

                                </div>

                            </form>

                        </div>

                    </div>

                    <div class="shadow-border">&nbsp;</div>

                    <?php echo $this->layout()->content; ?>

              </div>

               <div class="content-right">

				<div class="box">

                    <?php if( !isset($_SESSION['user'] ) ): ?>

				    <div class="head">

					   <h1>Inloggen</h1>

				    </div>

				    <div class="box-content" id="first-box">

					   <div id="login">
						  <div class="errors"></div>
						  <div class="profile-img"><img src="assets/img/user.png"/></div>

						  <form action="checklogin" method="POST" id="inloggen" autocomplete="off">

							 <div class="user-field">

								<input type="text" name="email" id="email" placeholder="E-mail"/>

							 </div>

							 <div class="key-field">

								<input type="password" name="password" id="password" placeholder="Wachtwoord"/>

							 </div>

							 <div class="login-box">

								<div id="switch" class="switch"><input type="hidden" name="remember" value="0"/></div>
								<span>Onthoud mij</span>
								<input type="submit" id="submit" value="Inloggen"/>

							 </div>

						  </form>

                          <a href="wachtwoord-vergeten" class="submit vergeten">Wachtwoord vergeten?</a>

					   </div>

				    </div>
				    
                <div class="shadow-border-2">&nbsp;</div>

				</div>

				<div class="box">

				    <div class="head">

					   <h1>Registreren</h1>

				    </div>

				    <div class="box-content">

					   <div id="registreren">

						  <div class="errors"></div>
						  <form action="registreren" id="register" method="POST" autocomplete="off">


							 <div class="user-field">

								<input type="text" name="email" id="email" placeholder="E-mail"/>

							 </div>

							 <div class="user-field">

								<input type="text" name="name" id="name" placeholder="Naam"/>

							 </div>

							 <div class="key-field">

								<input type="password" name="rpassword" id="rpassword" placeholder="Wachtwoord"/>

							 </div>

							 <div class="key-field">

								<input type="password" name="rpassword2" id="rpassword2" placeholder="Wachtwoord herhalen"/>

							 </div>

							 <input type="submit" name="submit" id="submit" value="Registreren"/>

						  </form>

					   </div>

				    </div>

                    <?php else: 

                    $user = $db->fetchRow('SELECT * FROM users WHERE email = ?', $_SESSION['user']);
                    $total_questions = count( $db->fetchAll('SELECT * FROM questions WHERE user_id = ?', $user['id']) );
                    $total_answers = count( $db->fetchAll('SELECT * FROM answers WHERE user_id = ?', $user['id']) );

                    ?>

                    <div class="head">

                       <h1>Welkom, <?php echo $user['name']; ?></h1>

                    </div>

                    <div class="box-content">

                       <div id="login" class="loginFix">

                        <?php if($user['image']): ?>
					       
                            <div class="circular" style="background: url('uploads/images/<?php echo $user['image']; ?>') no-repeat center center">&nbsp;</div>

                         <?php else: ?>

                          <div class="profile-img"><img src="assets/img/user.png"/></div>

                        <?php endif; ?>

                          <ul class="user_info">

    						<li class="dark"><span class="gestelde-vragen">Mijn gestelde vragen: <a href="questions"><?= $total_questions ?></a></span></li>
    						<li class="light"><span class="beantwoorde-vragen">Mijn beantwoorde vragen: <a href="questions"><?= $total_answers ?></a></span></li>
    						<li class="dark"><span class="stel-een-vraag"><a href="steleenvraag">Stel een vraag</a></span></li>

                          </ul>

                          <ul class="short_nav">

                            <li class="edit"><a href="profiel">Profiel bewerken</a></li>
                            <li class="logout"><a href="uitloggen">Uitloggen</a></li>

                          </ul>

                       </div>

                    </div>

                <?php endif; ?>

				    <div class="shadow-border-2">&nbsp;</div>

				</div>

                <div class="box">

                    <div class="head">

                       <h1>Laatste 3 vragen</h1>

                    </div>

                    <div class="box-content">

                       <div id="top-3">

                            <ul>
                                <?php 
                                    $top3 = $db->fetchAll('SELECT * FROM questions WHERE date_created > DATE_SUB(NOW(), INTERVAL 24 HOUR) ORDER BY date_created DESC LIMIT 3');
        							if(!$top3):
                                ?>
        						
                                        <li>Er zijn geen vragen gesteld vandaag.</li>        						

								<?php 
                                    else:
                                    foreach($top3 as $question):

                                        if (strlen($question['name']) <= 30)
                                            $question['name'] = $question['name'];
                                        else
                                            $question['name'] = substr($question['name'], 0, strpos(wordwrap($question['name'], 30), "\n")) . "... ?";
                                ?>
                                        <li class="favo"><a href="question/<?= $question['url'] ?>"><?= ucfirst(strtolower($question['name'])) ?></a></li>

                                <?php
                                    endforeach;
                                    endif;
                                ?>
                            </ul>

                       </div>

                    </div>
                    
                <div class="shadow-border-2">&nbsp;</div>

                </div>

                <div class="box">

                    <div class="head">

                       <h1>Facebook</h1>

                    </div>

                    <div class="box-content">
<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fhetvragenboekje&amp;width=292&amp;height=258&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;show_border=false&amp;header=false&amp;appId=117716921766168" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:258px; margin: 45px 0 0 0; " allowTransparency="true"></iframe>
                       
                    </div>
                    
                <div class="shadow-border-2">&nbsp;</div>

                </div>

			 </div>

        </div>

    </div>

    <div class="footer clearfix">

        <div class="centered">

                <div class="footer-row">

                    <h2>Sitemap</h2>

                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Copyright</a></li>
                        <li><a href="#">Mobiel</a></li>
                        <li><a href="#">Algemene voorwaarden</a></li>
                    </ul>

                </div>

                <div class="footer-row">

                    <h2>Categorieën</h2>

                    <ul>
                        <li><a href="categorieen/computers-en-internet">Computers &amp; Internet</a></li>
                        <li><a href="categorieen/elektronica">Elektronica</a></li>
                        <li><a href="categorieen/entertainment-en-muziek">Entertainment &amp; Muziek</a></li>
                        <li><a href="categorieen/eten-en-drinken">Eten &amp; Drinken</a></li>
                        <li><a href="categorieen/financien-en-werk">Financien &amp; Werk</a></li>
                        <li><a href="categorieen/huis-en-tuin">Huis &amp; Tuin</a></li>
                    </ul>

                </div>

                <div class="footer-row">

                    <h2>&nbsp;</h2>

                    <ul>
                        <li><a href="categorieen/kunst-en-cultuur">Kunst &amp; Cultuur</a></li>
                        <li><a href="categorieen/maatschappij">Maatschappij</a></li>
                        <li><a href="categorieen/overig">Overig</a></li>
                        <li><a href="categorieen/persoon-en-gezondheid">Persoon &amp; Gezondheid</a></li>
                        <li><a href="categorieen/sport-spel-en-recreatie">Sport, spel &amp; recreatie</a></li>
                        <li><a href="categorieen/vakantie-en-reizen">Vakantie &amp; Reizen</a></li>
                    </ul>

                </div>

                <div class="footer-row">

                    <h2>Mijnvragenboekje.nl</h2>

                    <ul>
                        <li><a href="#">Over ons</a></li>
                        <li><a href="#">F.A.Q.</a></li>
                        <li><a href="#">Regels</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Inloggen</a></li>
                        <li><a href="#">Registreren</a></li>
                    </ul>

                </div>

                <div class="bottom">

                    <span>Copyright &copy; hetvragenboekje.nl - Ertugrul Kat, Fons Hettema, Jason Imanuel ® All rights reserved.</span>

                </div>

        </div>

    </div>

    <script type="text/javascript" src="assets/js/validate.js"></script>
    <script type="text/javascript" src="assets/js/js.js"></script>

  </body>

</html>
