<?php
 $config = Zend_Registry::get('config');
 $db = Zend_Registry::get('db');
 $request = Zend_Controller_Front::getInstance()->getRequest();
?>
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <base href="<?= $config->baseurl; ?>" />
    <title>Questions and Answers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">

    <!-- Le styles -->
    <link href="assets/css/reset.css" rel="stylesheet">
    <link href="assets/css/main.css" rel="stylesheet">

    <!-- Le fonts -->
    <link href='http://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>

    <!-- Le bootstrap -->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  </head>

  <body>

    <div class="top">

        <div class="centered">

            <div class="logo">&nbsp;</div>

        </div>

    </div>

    <div class="menu">

        <div class="centered">

            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Categorieën</a></li>
            </ul>

        </div>

    </div>

    <div class="container">

        <div class="content clearfix">

              <div class="content-left">

                <div class="search">

                    <div class="search-img">&nbsp;</div>

                    <div class="search-box">

                        <p>De leukste vragensite van Nederland met mogelijheden tot printen op A5 formaat!</p>

                        <form action="#" method="POST">

                            <div class="search-bar">

                                <input type="search" name="s" placeholder="Zoek op vragen.." />

                            </div>

                        </form>

                    </div>

                </div>

                <div class="shadow-border">&nbsp;</div>

                <h1 class="header">Vragen</h1>

                <div class="shadow-border">&nbsp;</div>

                <div class="question">

                    <div class="question-image">
                    
                        <img src="assets/img/preview.png" />

                    </div>

                    <div class="question-info">

                        <span>Wat is het beste voor Nederland?</span>
                        
                        <p>
                            Je kon de hele avond je vraag aan Mr. X naar 5380 sms’en & dat is 
                            ook massaal gedaan! Barry stelde er een aantal aan Mr. X himself. 
                            Zo weten we nu dat ‘ie niet in een Mini Cooper rijdt, z’n favo food 
                            een Mexicaanse ovenschotel is & dat ‘ie ook graag langs...
                        </p>

                    </div>

                </div>

                <div class="shadow-border">&nbsp;</div>

              </div>

              <div class="content-right">

                <p>TEST</p>

              </div>

        </div>

    </div>

    <div class="footer">


    </div>

  </body>

</html>
