<div class="register">

    <h2>Registreren</h2>

    <?php if( $this->error ): ?>

        <?= $this->error; ?>

    <?php endif; ?>

    <form action="registreren" method="POST">

        <fieldset>

            <?php echo $this->form->getElement('email'); ?><br />
            <?php echo $this->form->getElement('name'); ?><br />
            <?php echo $this->form->getElement('password'); ?><br />
            <input type="password" name="password2" id="password" placeholder="Wachtwoord herhalen..." /><br />
            <input type="submit" name="submit" id="submit" value="Registreren" />

        </fieldset>

    </form>

</div>