<h1 class="header">

   <span class="header-bg">Disclaimer</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>
<div id="info">
    <h2>DISCLAIMER - VRIJWARING</h2>
<p>Ondanks de constante zorg en aandacht die wij besteden aan de samenstelling van deze site en de daarin opgenomen gegevens, kunnen Hetvragenboekje.nl en haar groepsmaatschappijen (hierna tezamen aangeduid als: "Hetvragenboekje.nl") niet instaan voor de volledigheid, juistheid of voortdurende actualiteit van de gegevens en de inhoud van de site. Hetvragenboekje.nl aanvaardt dan ook geen aansprakelijkheid voor enigerlei directe of indirecte schade, van welke aard ook, die voortvloeit uit of in enig opzicht verband houdt met het gebruik van de site of de (on)bereikbaarheid van de site.
</p>
<p>
Beweringen en meningen, geuit in artikelen en mededelingen op de pagina's van deze site, zijn die van de auteur(s) en niet (noodzakelijkerwijs) die van de webmaster, de internetprovider of Hetvragenboekje.nl. Hetvragenboekje.nl kan op geen enkele manier verantwoordelijk worden gehouden voor de inhoud hiervan en is niet aansprakelijk voor enigerlei directe of indirecte schade die mogelijk voortvloeit uit de betreffende uitingen.
Hetvragenboekje.nl kan er niet voor instaan dat de informatie op deze site geschikt is voor het doel waarvoor de informatie door u wordt geraadpleegd. Alle informatie, producten en diensten worden aangeboden in de staat waarin deze zich feitelijk bevinden en zonder enige (impliciete) garantie of waarborg ten aanzien van hun deugdelijkheid, geschiktheid voor een bepaald doel of anderszins.
</p>
<p>
Hetvragenboekje.nl garandeert noch ondersteunt enige product of enige dienst genoemd op deze site, noch staat zij garant voor enige door de vervaardiger van dergelijke producten gedane bewering. Met het oog hierop wordt de gebruiker van deze site altijd aangeraden onafhankelijke inlichtingen in te winnen en/of onderzoek te verrichten voor gebruik van via deze site verkregen informatie.
De informatie op deze site wordt regelmatig aangevuld en/of aangepast. Hetvragenboekje.nl behoudt zich het recht voor om eventuele wijzigingen met onmiddellijke ingang en zonder enige kennisgeving door te voeren.</p>

<h2>LINKS NAAR ANDERE WEBSITES</h2>
<p>Op deze site treft u een aantal links aan naar andere websites. Hetvragenboekje.nl is niet aansprakelijk voor de inhoud van die sites en/of de wijze waarop die sites omgaan met uw (persoons)gegevens. Lees hiervoor het privacy beleid, de disclaimer, de copyright notice en algemene voorwaarden,indien aanwezig,van de site die u bezoekt.</p>

</div>

