<h1 class="header">

   <span class="header-bg">F.A.Q.</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>
<div id="info">
    <h2>Een vraag stellen</h2>
<p>Bereik heel Nederland. Stel je vraag online op Hetvragenboekje.nl en alle andere gebruikers kunnen meteen antwoord geven.</p>

<h2>Een vraag beantwoorden</h2>
<p>Help anderen en geef antwoord op recent gestelde vragen. Deel je kennis.</p>

</div>

