<h1 class="header">

   <span class="header-bg">F.A.Q.</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>
<div id="info">
    <h2>Algemeen</h2>
    <h3>Wat is Hetvragenboekje.nl?</h3>
    <p>Hetvragenboekje.nl is een website waar je vragen kunt stellen. Deze vragen worden beantwoord door andere gebruikers van Hetvragenboekje.nl.</p>
    <h3>Is Hetvragenboekje.nl gratis?</h3>
    <p>Ja, Hetvragenboekje.nl is helemaal gratis..</p>
    <h3>Hoe werkt Hetvragenboekje.nl?</h3>
    <p>Klik <span class="handleiding"><a href="#">hier</a></span> voor de handleiding.</p>
</div>

