<h1 class="header">

   <span class="header-bg">Richtlijnen</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>
<div id="info">

<p>Hetvragenboekje.nl is een vraag & antwoordplatform en heeft tot doel kennis te ontwikkelen en te delen. Dat gebeurt door het stellen van vragen en het geven van antwoorden. Hetvragenboekje.nl is een kennisplatform en dus geen discussieforum, chatbox of Marktplaats.</p>

<p>De bijdrage moet nadrukkelijk een vraag, antwoord of reactie op een vraag of antwoord zijn. De richtlijnen worden hieronder toegelicht. Als de bijdrage niet aan de regels voldoet, kan het moderatieteam de bijdrage verwijderen of aanpassen.</p>

</div>

