<h1 class="header">

   <span class="header-bg">Algemene voorwaarden</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>
<div id="info">
    <p>Hier volgt de verkorte en versimpelde versie van de Algemene Voorwaarden. Alhoewel deze korte versie wel een stuk lekkerder wegleest, zijn alleen de uitgebreide Algemene Voorwaarden van toepassing. </p>
    <h2>Algemeen</h2>
<p>De vragen en antwoorden op Hetvragenboekje.nl worden geplaatst door gebruikers. De informatie die uit gestelde vragen voortkomt dient daarom te worden beschouwd met een dosis gezond verstand, en niet als expert-advies te worden beschouwd.</p>

<h2>Privacy</h2>
<p>Hetvragenboekje.nl  gaat zorgvuldig om met je persoonlijke informatie. We vragen je alleen om de gegevens die nodig zijn om het systeem te kunnen gebruiken, en delen deze gegevens niet met andere partijen.</p>

<h2>Gedragsrichtlijnen</h2>
<p>
Gedraag je netjes: plaats geen spam, pornografische, racistische of beledigende inhoud. Goeie Vraag en zijn moderatoren hebben altijd het recht om gebruikers, vragen, antwoorden en reacties te wijzigen en/of verwijderen als hiertoe reden is.</p>

<h2>Copyright</h2>
<p>
Je behoudt alle eigendomsrechten op inhoud die door jou is geplaatst, maar stemt ermee in dat jouw inhoud wordt getoond op Hetvragenboekje.nl en andere websites / applicaties.
    </p>
  

</div>

