<h1 class="header">

   <span class="header-bg">Waarvoor wil je contact opnemen?</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>

<div class="contact">

   <p>

      <select id="contact_select">

         <option value="">Selecteer je reden...</option>
         <option value="vraagstellen">Ik wil een vraag stellen op Het Vragenboekje.nl</option>
         <option value="melden">Ik wil een ongepaste vraag/antwoord/reactie melden</option>
         <option value="inloggen">Ik kan niet meer inloggen</option>
         <option value="activiteit">Ik heb een vraag of opmerking over mijn activiteit op Het Vragenboekje</option>
         <option value="inhoud">Ik wil melding maken van een probleem met de inhoud van een pagina op Het Vragenboekje</option>
         <option value="werking">Ik wil melding maken van een probleem met de werking van een pagina op Het Vragenboekje</option>

      </select>

   </p>

   <div class="contact_option" id="contact_vraagstellen" style="display: none;">

      <p>Je kunt <a href="steleenvraag">je vraag stellen</a> door je vraag te typen in de 'Stel je vraag' box die bovenaan elke pagina te vinden is.</p>

   </div>

   <div class="contact_option" id="contact_melden" style="">

      <p>Je kunt vragen, antwoorden en reacties die niet stroken met de <a href="richtlijnen">richtlijnen</a> of <a href="voorwaarden">voorwaarden</a> melden aan het moderatie-team via de link <em>'melden'</em>, die onder elke vraag/antwoord/reactie te vinden is.</p>

   </div>

   <div class="contact_option" id="contact_inloggen" style="display: none;">

      <p>Als je niet meer kunt inloggen omdat je je wachtwoord vergeten bent, maak dan gebruik van <a href="wachtwoord-vergeten">de “Wachtwoord vergeten?” mogelijkheid</a>. Nadat je daar je e-mailadres hebt ingevuld, ontvang je per e-mail een link waarmee je een tijdelijke mogelijkheid hebt om je wachtwoord te veranderen.</p>

   </div>


   <div class="contact_option contact_werking contact_inhoud contact_activiteit" id="contact_beheerders" style="display: none;">

      <p>Gebruik dit formulier om contact op te nemen met de beheerders.</p>

      <form method="post" action="contactsend" class="tableless validate">

         <div>
            
            <label for="name">Naam:<sup>*</sup></label><br>
            <input type="text" name="name" id="name" value="" size="25" class="required magenta"><br>

            <label for="username">Gebruikersnaam:</label><br>
            <input type="text" name="username" id="username" value="" class="magenta" size="25"><br>

            <label for="email">E-mail:<sup>*</sup></label><br>
            <input type="text" name="email" id="email" value="" size="25" class="required email magenta"><br>

            <label for="subject">Onderwerp:<sup>*</sup></label><br>
            <input type="text" name="subject" id="subject" value="" size="50" class="required full magenta"><br>

            <label for="message">Bericht:<sup>*</sup></label><br>

            <textarea name="message" id="message" cols="50" rows="1" class="required expanding full spellcheck growfield magenta" style="overflow: hidden; height: 60px;"></textarea>

            <span class="error_location message"></span><br>

            <input type="submit" class="submit" value="Versturen" id="submit"><br>

         </div>

      </form>

   </div>

</div>

<script type="text/javascript">

$(function() {
	$('#contact_select').on('change', function() {
	  $('.contact_option').hide()
	  if($(this).val() != '') {
		$('.contact_'+ $(this).val() + ',#contact_'+ $(this).val()).show();
		$('#reason').val($(this).val());
	  }
	});
});

</script>