<!-- TO DO: DESIGN NIEUWE VRAAG VORMGEVING -->



<h1 class="header">Vragen</h1>
<span id="email-error"class="hidden"><?=$this->error?></span>

<div class="shadow-border">&nbsp;</div>

<?php 
    $db = Zend_Registry::get('db');

    foreach($this->questions as $question): 
	
    $category = $db->fetchRow('SELECT name, url FROM categories WHERE id = ?', $question['category_id']);
    $answers = count( $db->fetchAll('SELECT * FROM answers WHERE question_id = ?', $question['id']) );
    $tags = explode(';', $question['tags']);

    $question_ratings = $db->fetchAll('SELECT * FROM votes WHERE question_id = ?', $question['id']);
    $user = $db->fetchOne('SELECT name FROM users WHERE id = ?', $question['user_id']);

    foreach($question_ratings as $question_rating)
        $question_rating = $question_rating['total'] / $question_rating['votes'];
    
    $date = new Zend_Date($question['date_created']);

    ($answers == 0 ? $answers = "Nog niet beantwoord." : $answers .= "x beantwoord");
    
?>

    <div class="question">

        <div class="question-image">
        
            <img src="assets/img/preview.png" />

        </div>

        <div class="question-info">

            <a href="categorieen/<?= $category['url'] ?>" class="category"><?php echo $category['name']; ?></a>
            
            <p>
                <a href="question/<?= $question['url'] ?>" class="title"><?php echo $question['name']; ?></a><br />
                <a href="question/<?= $question['url'] ?>" class="title"><?php echo $user; ?></a>
            </p>

		  
        </div>
	   
	   <div class="question-data">
		  
		  <span class="date">Geplaatst <?php echo $date->toString("dd-MMMM-YYYY");?></span>
		  
		  <span class="answers"><img src="assets/img/comment.png"/><?php echo $answers;?></span>
		  
		  <span class="votes"><img src="assets/img/up.png"/>+<?php echo $votes = 0;?></span>
		  
	   </div>

    </div>

    <div class="shadow-border">&nbsp;</div>

<?php endforeach; ?>