<?php
 $db = Zend_Registry::get('db'); 
 $cname = str_replace("&", "en", $this->category['name']);
 $sharelink = "https://www.facebook.com/dialog/feed?app_id=" . $this->appID . "&link=" . $this->baseurl . 'question/' .$this->question['url'] . "&picture=". $this->baseurl . "assets/img/fb.png&name=" . $this->question['name'] . "&caption=" . $cname . "&redirect_uri=" . $this->baseurl . 'question/' . $this->question['url'];

$tags = array();

if($this->question['tags'])
{
    $twittertag = ",";
    $twittertag .= str_replace(";",",",$this->question['tags']);
}

if(!empty($this->question['tags']))
    $tags = explode(';', $this->question['tags']);


?>

<h1 class="header">Vraag</h1>

<div class="shadow-border">&nbsp;</div>

<div class="question">

    <div class="question-image">
    
        <img src="assets/img/categories/150x150/<?= $this->question['category_id'] ?>.png" />

    </div>

    <div class="question-info">

        <a href="categorieen/<?= $this->category['url'] ?>" class="category"><?php echo $this->category['name']; ?></a>
        
        <p>
            <span class="question-title"><?php echo $this->question['name']; ?></span>
            <a href="<?= $sharelink ?>" class="fb-share">Share</a>
            <a href="https://twitter.com/share?url=<?=$this->baseurl.'question/'.$this->question['url'];?>&counturl=<?=$this->baseurl.'question/'.$this->question['url'];?>&hashtags=HetVragenboekje,<?=str_replace(" & ", ",", $this->category['name']).$twittertag;?>&text=<?=(strlen($this->question['name']) > 20) ? substr($this->question['name'],0,20).'...' : $this->question['name'];?>" class="twitter-share">Tweet</a>
        </p>

    </div>

     <div class="question-data">
          
          <span class="date">Geplaatst <?php echo $this->questiondate;?></span>

          <?php if(isset($_SESSION['user'] ) && $this->answers): ?>

            <span class="print">

                <img src="assets/img/print.png"/>

                <?php
                    $answer_id = $db->fetchOne('SELECT id FROM answers 
                                                  WHERE question_id = ? 
                                                  ORDER BY date_created DESC 
                                                  LIMIT 1', $this->question['id']);

                    foreach($this->answers as $answer): 

                        $answerer = $db->fetchRow('SELECT * FROM users WHERE id = ?', $answer['user_id']);
                        $thumbs = $db->fetchAll('SELECT * FROM thumbs WHERE answer_id = ?', $answer['id']);
                        $answerdate = new Zend_Date($answer['date_created']);

                        if( isset($thumbs) ) {
                            foreach($thumbs as $thumb)
                            $answer_id = $db->fetchOne('SELECT answer_id, COUNT(answer_id) AS a_id FROM thumbs WHERE question_id = ? GROUP BY answer_id ORDER BY a_id DESC LIMIT 1', $this->question['id']);
                        }

                    endforeach;
	   
                ?>
		  
                <a target="_blank" href="createpdf?q=<?= $this->question['id'] ?>&a=<?= $answer_id ?>">Print als PDF</a>

            </span>

          <?php endif; ?>
          
          <span class="answers"><img src="assets/img/comment.png"/><?php echo $this->countedAnswers;?></span>
          <span class="user"><?php echo $this->questioner['name'] ?></span>
          
       </div>

</div>

<div class="shadow-border">&nbsp;</div>

<div class="tags">

    <?php foreach($tags as $tag): echo '<span><a href="tag/' . $tag . '">#' . $tag . '</a></span>'; endforeach; ?>

</div>

<div id="overview">

    <?php if( $this->answers ): ?>

        <h1 class="header">Antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>

        <?php 

        foreach($this->answers as $answer):

            $answerer = $db->fetchRow('SELECT * FROM users WHERE id = ?', $answer['user_id']);
            $thumbs = $db->fetchAll('SELECT * FROM thumbs WHERE answer_id = ?', $answer['id']);
            $answerdate = new Zend_Date($answer['date_created']);

            foreach($thumbs as $thumb)
                $answer_id = $db->fetchOne('SELECT answer_id, COUNT(answer_id) AS a_id FROM thumbs GROUP BY answer_id ORDER BY a_id DESC LIMIT 1');

        ?>        

            <div class="question">

                <div class="question-image">
                
                    <?php if($answerer['image']): ?>
                        <img width="150" height="150" src="uploads/images/<?php echo $answerer['image'] ?>" />
                    <?php else: ?>
                        <img src="assets/img/profile_unknown.png" />
                    <?php endif; ?>

                </div>

                <div class="question-info">

                    <span style="display: block; float: left; margin-right: 5px;">Beantwoord door:</span><span class="answerer"><?php echo $answerer['name']; ?></span>
                    
                    <p class="answer-title"><?php echo $answer['name']; ?></p>

                </div>

                 <div class="question-data">
                      
                      <span class="date">Beantwoord <?php echo $answerdate->toString("dd MMMM YYYY"); ?></span>

                      <?php 
                        $arrIds = array();
                        foreach($thumbs as $thumb)
                            $arrIds[] = $thumb['user_id'];

                        if( in_array($this->user['id'], $arrIds) || !isset($_SESSION['user']) )
                            echo '<span class="thumbs"><img style="margin: 0 5px 0 0;" src="assets/img/up-active.png"/>+'. count ( $thumbs ) . '</span>';
                        else
                            echo '<span class="votes"><img class="thumbs-up" src="assets/img/up.png"/>+<span data-user="' . $this->user['id'] . '" data-answer="' . $answer['id'] . '" data-question="' . $this->question['id'] . '" data-thumb="' . count ( $thumbs ) . '">' . count ( $thumbs ) . '</span></span>';
				    
				   ?>
                   </div>

            </div>

            <div class="shadow-border">&nbsp;</div>

        <?php endforeach; ?>

    <?php else: ?>

        <h1 class="header">Geen antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>
    
    <?php endif; ?>

    <?php if(isset($_SESSION['user'] )): ?>

    <div id="formulier">

        <form action="antwoord" id="answer_form" method="POST">

            <fieldset>

                <label for="name">Beantwoord deze vraag</label>
                <?php echo $this->form->getElement('name'); ?><br /><br />

                <input type="hidden" name="question_id" value="<?php echo $this->question['id']; ?>" />
                <input type="hidden" name="question_name" value="<?php echo sanitize($this->question['name']); ?>" />

                <input type="submit" name="submit" class="submit" value="Antwoord">

            </fieldset>

        </form>

    </div>

    <?php endif; ?>

    <script type="text/javascript" src="assets/js/thumbsup.js"></script>

</div>