<?php
 $db = Zend_Registry::get('db'); 
?>

<h1 class="header">Vraag</h1>

<div class="shadow-border">&nbsp;</div>

<!--<div class="question">

    <a class="answers"><?php echo count( $this->answers ); ?></a>

    <a id="category" href="categorieen/<?php echo $this->category['url']; ?>"><?php echo $this->category['name']; ?></a>

    <span class="stars"><?php if($this->question_rating): echo $this->question_rating; else: echo '0'; endif; ?></span>

    <a class="print" href="printToPDF">&nbsp;</a>

    <span class="q"><?php echo $this->question['name']; ?></span>
    <span class="user"><a href="question/is-een-banaan-echt-wel-zo-gezond"><?php echo $this->questioner['name']; ?></a> vraagt..</span>

    <div class="tags">

        <?php foreach($this->tags as $tag) echo '<span>' . $tag . '</span>'; ?>

    </div>

</div>-->

<!-- // TO DO: VRAAG FIXEN MET NIEUW DESIGN -->

<div class="question">

    <div class="question-image">
    
        <img src="assets/img/preview.png" />

    </div>

    <div class="question-info">

        <a href="categorieen/<?= $this->category['url'] ?>" class="category"><?php echo $this->category['name']; ?></a>
        
        <p>
            <a href="question/<?= $this->question['url'] ?>" class="title"><?php echo $this->question['name']; ?></a><br />
            <a href="question/<?= $this->question['url'] ?>" class="title"><?php echo $user; ?></a>
        </p>

    </div>

     <div class="question-data">
		  
		  <span class="date">Geplaatst <?php echo $this->date;?></span>
		  
		  <span class="answers"><img src="assets/img/comment.png"/><?php echo $this->countedAnswers;?></span>
		  
		  <span class="votes"><img src="assets/img/up.png"/>+<?php echo $votes = 0;?></span>
		  
	   </div>
</div>

<div class="shadow-border">&nbsp;</div>

<div id="overview">

	<?php if( $this->answers ): ?>

        <h1 class="header">Antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>

        <?php 

        foreach($this->answers as $answer): 

            $answerer = $db->fetchRow('SELECT * FROM users WHERE id = ?', $answer['user_id']);?>        

            <!--

            // TO DO: ANTWOORDEN FIXEN MET NIEUW DESIGN

    		<div class="answer">

    		    <span class="stars"><?php if($this->answer_rating): echo $this->answer_rating; else: echo '0'; endif; ?></span>

    		    <span class="a"><?php echo $answer['name']; ?></span>

                <span class="user"><?php echo $answerer['name']; ?> antwoord..</span>

    		</div>
            -->

            <div class="answer">

                <div class="answer-image">
                
                    <img src="assets/img/preview.png" />

                </div>

                <div class="answer-info">

                    <span style="display: block; float: left; margin-right: 5px;">Beantwoord door:</span><a href="categorieen/<?= $category['url'] ?>" class="category"><?php echo $answerer['name']; ?></a>
                    
                    <p class="title"><?php echo $answer['name']; ?></p>

                </div>

            </div>

    <div class="shadow-border">&nbsp;</div>

        <?php endforeach; ?>

    <?php else: ?>

        <h1 class="header">Geen antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>
    
    <?php endif; ?>

    <?php if(isset($_SESSION['user'] )): ?>

        <form action="antwoord" id="answer_form" method="POST">

            <fieldset>

                <label for="answer">Beantwoord deze vraag</label>
                <?php echo $this->form->getElement('name'); ?>
                <input type="hidden" name="question_id" value="<?php echo $this->question['id']; ?>" />
                <input type="hidden" name="question_name" value="<?php echo sanitize($this->question['name']); ?>" />

                <input type="submit" name="submit" class="btn-primary submit" value="Antwoord">

            </fieldset>

        </form>

    <?php endif; ?>

</div>