<?php
 $db = Zend_Registry::get('db'); 
?>

<h1 class="header">Vraag</h1>

<div class="shadow-border">&nbsp;</div>

<!--<div class="question">

    <a class="answers"><?php echo count( $this->answers ); ?></a>

    <a id="category" href="categorieen/<?php echo $this->category['url']; ?>"><?php echo $this->category['name']; ?></a>

    <span class="stars"><?php if($this->question_rating): echo $this->question_rating; else: echo '0'; endif; ?></span>

    <a class="print" href="printToPDF">&nbsp;</a>

    <span class="q"><?php echo $this->question['name']; ?></span>
    <span class="user"><a href="question/is-een-banaan-echt-wel-zo-gezond"><?php echo $this->questioner['name']; ?></a> vraagt..</span>

    <div class="tags">

        <?php foreach($this->tags as $tag) echo '<span>' . $tag . '</span>'; ?>

    </div>

</div>-->

<!-- // TO DO: VRAAG FIXEN MET NIEUW DESIGN -->

<div class="question">

    <div class="question-image">
    
        <img src="assets/img/preview.png" />

    </div>

    <div class="question-info">

        <a href="categorieen/<?= $this->category['url'] ?>" class="category"><?php echo $this->category['name']; ?></a>
        
        <p>
            <a href="question/<?= $this->question['url'] ?>" class="title"><?php echo $this->question['name']; ?></a><br /><br />
            <a href="question/<?= $this->question['url'] ?>" class="title"><?php echo $this->user['name']; ?></a>
        </p>

    </div>

     <div class="question-data">
          
          <span class="date">Geplaatst <?php echo $this->questiondate;?></span>

          <?php if(isset($_SESSION['user'] )): ?>

            <span class="print">

                <img src="assets/img/print.png"/>

                <!-- ANTWOORD ID PAKKEN MET MEESTE THUMBS EN PLAATSEN -->

                <?php

                    foreach($this->answers as $answer): 

                        $last_answer = $db->fetchOne('SELECT id FROM answers WHERE question_id = ? ORDER BY date_created LIMIT 1', $this->question['id']);
                        $answerer = $db->fetchRow('SELECT * FROM users WHERE id = ?', $answer['user_id']);
                        $thumbs = $db->fetchAll('SELECT * FROM thumbs WHERE answer_id = ?', $answer['id']);
                        $answerdate = new Zend_Date($answer['date_created']);
                        $answer_id = '';

                        if( $thumbs ):
                            foreach($thumbs as $thumb)
                            $answer_id = $db->fetchOne('SELECT answer_id, COUNT(answer_id) AS a_id FROM thumbs WHERE question_id = ? GROUP BY answer_id ORDER BY a_id DESC LIMIT 1', $this->question['id']);
                        endif;

                        if( ! count( $answer_id ) )
                            $answer_id = $last_answer;

                    endforeach;

                ?>

                <a target="_blank" href="createpdf?q=<?= $this->question['id'] ?>&a=<?= $answer_id ?>">Print als PDF</a>

            </span>

          <?php endif; ?>
          
          <span class="answers"><img src="assets/img/comment.png"/><?php echo $this->countedAnswers;?></span>
          
       </div>
</div>

<div class="shadow-border">&nbsp;</div>

<div class="tags">

    <?php foreach($this->tags as $tag) echo '<span>#' . $tag . '</span>'; ?>

</div>

<div id="overview">

    <?php if( $this->answers ): ?>

        <h1 class="header">Antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>

        <?php 

        foreach($this->answers as $answer): 

            $answerer = $db->fetchRow('SELECT * FROM users WHERE id = ?', $answer['user_id']);
            $thumbs = $db->fetchAll('SELECT * FROM thumbs WHERE answer_id = ?', $answer['id']);
            $answerdate = new Zend_Date($answer['date_created']);

            foreach($thumbs as $thumb)
                $answer_id = $db->fetchOne('SELECT answer_id, COUNT(answer_id) AS a_id FROM thumbs GROUP BY answer_id ORDER BY a_id DESC LIMIT 1');


        ?>        

            <div class="question">

                <div class="question-image">
                
                    <img src="assets/img/preview.png" />

                </div>

                <div class="question-info">

                    <span style="display: block; float: left; margin-right: 5px;">Beantwoord door:</span><a href="categorieen/<?= $category['url'] ?>" class="category"><?php echo $answerer['name']; ?></a>
                    
                    <p class="title"><?php echo $answer['name']; ?></p>

                </div>

                 <div class="question-data">
                      
                      <span class="date">Beantwoord <?php echo $answerdate->toString("dd MMMM YYYY"); ?></span>

                      <?php 
                        $arrIds = array();
                        foreach($thumbs as $thumb)
                            $arrIds[] = $thumb['user_id'];

                        if( in_array($this->user['id'], $arrIds) )
                            echo '<span class="thumbs"><img style="margin: 0 5px 0 0;" src="assets/img/up-active.png"/>+'. count ( $thumbs ) . '</span>';
                        else
                            echo '<span class="votes"><img id="thumbs-up" src="assets/img/up.png"/>+<span data-user="' . $this->user['id'] . '" data-answer="' . $answer['id'] . '" data-question="' . $this->question['id'] . '" data-thumb="' . count ( $thumbs ) . '">' . count ( $thumbs ) . '</span></span>';
                      ?>
                      
                   </div>

            </div>

            <div class="shadow-border">&nbsp;</div>

        <?php endforeach; ?>

    <?php else: ?>

        <h1 class="header">Geen antwoorden</h1>

        <div class="shadow-border">&nbsp;</div>
    
    <?php endif; ?>

    <?php if(isset($_SESSION['user'] )): ?>

    <div id="formulier">

        <form action="antwoord" id="answer_form" method="POST">

            <fieldset>

                <label for="name">Beantwoord deze vraag</label>
                <?php echo $this->form->getElement('name'); ?><br /><br />

                <input type="hidden" name="question_id" value="<?php echo $this->question['id']; ?>" />
                <input type="hidden" name="question_name" value="<?php echo sanitize($this->question['name']); ?>" />

                <input type="submit" name="submit" class="submit" value="Antwoord">

            </fieldset>

        </form>

    </div>

    <?php endif; ?>

    <script type="text/javascript" src="assets/js/thumbsup.js"></script>

</div>