<!DOCTYPE html>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Het vragenboekje</title>
	   <link rel="stylesheet" href="assets/css/pdf.css" type="text/css"/>
    </head>
    <body>
	   <div id="question">
		  <div id="logo"></div>
		  <h1 class="header">Vraag </h1>
		  <div class="shadow-border1">&nbsp;</div>
		  <div class="question">
			 <div class="question-image">
                	<img src="assets/img/categories/150x150/<?php echo $this->data['category']['id'] ?>.png" />
				<span class="magenta"><?php echo $this->data['userQ']; ?></span>
			 </div>
			 <div class="question-info">
				<span class="category"><?php echo $this->data['category']['name']; ?></span>
				<span class="title"><?php echo $this->data['question']['name']; ?></span><br /><br />
			 </div>
			 <div class="question-data">
				<span class="date">Geplaatst op: <?php echo $this->data['dateQ'];?></span>
			
				<span class="print"><img src="assets/img/print.png"><span>Geprint op: <?php echo $this->data['dateToday'];?></span></span>
			 </div>
		  </div>
		  <div class="shadow-border2">&nbsp;</div>
		  <h1 class="header">Antwoord </h1>
		  <div class="shadow-border3">&nbsp;</div>
		 <div class="answer">

                <div class="answer-image">
                	<?php if($this->data['userAimg']): ?>
                    	<img src="assets/img/<?php echo $this->data['userAimg'] ?>" />
                    <?php else: ?>
                    	<img src="assets/img/profile_unknown.png" />
                    <?php endif; ?>
					<span class="magenta"><?php echo $this->data['userA']; ?></span>
                </div>

                <div class="answer-info">
                    <span style="display: block; float: left; margin-right: 5px; height: 14px;"> </span>
                    <p class="title"><?php echo $this->data['answer']['name']; ?></p>
                </div>
			<div class="answer-data">
				<span class="date">Geplaatst op: <?php echo $this->data['dateA'];?></span>
				<span class="votes"><img src="assets/img/up-active.png"/>+<?php echo $this->data['thumbs'];?></span>
			</div>
            </div>
		  <div class="shadow-border2">&nbsp;</div>
	   </div>

	   <div id="notepad">
		  <img src="assets/img/notitie.png" width="700"/>
	   </div>
	  
	   <div id='cut-line'></div>
    </body>
</html>
