<h1 class="header">

  <?php if( count($this->questions) ): ?>
   
   <span class="header-bg">Mijn Vragen</span>

  <?php else: ?>

   <span class="header-bg">Geen vragen gesteld</span>

  <?php endif; ?>

</h1>

<div class="shadow-border-3">&nbsp;</div>

<?php 
    $db = Zend_Registry::get('db');
    $tags = array();

    foreach($this->questions as $question): 

    $category = $db->fetchRow('SELECT name, url FROM categories WHERE id = ?', $question['category_id']);
    $answers = count( $db->fetchAll('SELECT * FROM answers WHERE question_id = ?', $question['id']) );
    
    if(!empty($question['tags']))
        $tags = explode(';', $question['tags']);

    $user = $db->fetchOne('SELECT name FROM users WHERE id = ?', $question['user_id']);
    
    $date = new Zend_Date($question['date_created']);

    ($answers == 0 ? $answers = "Nog niet beantwoord" : $answers .= "x beantwoord");
    $cname = str_replace("&", "en", $category['name']);
     $sharelink = "https://www.facebook.com/dialog/feed?app_id=" . $this->appID . "&link=" . $this->baseurl . 'question/' . $question['url'] . "&picture=". $this->baseurl . "assets/img/fb.png&name=" . $question['name'] . "&caption=" . $cname . "&redirect_uri=" . $this->baseurl . 'question/' . $question['url'];

?>

    <div class="question">

        <div class="question-image">
        
            <a href="question/<?= $question['url'] ?>">
                
                <img src="assets/img/categories/150x150/<?= $question['category_id'] ?>.png" />
                
            </a>

        </div>

        <div class="question-info">

            <a href="categorieen/<?= $category['url'] ?>" class="category"><?php echo $category['name']; ?></a>
		  
            <p>
                <a href="question/<?= $question['url'] ?>" class="title"><?php echo $question['name']; ?></a>
                <a href="<?= $sharelink ?>" class="fb-share">Share</a>
                <a href="https://twitter.com/share?url=<?=$this->baseurl.'question/'.$question['url'];?>&counturl=<?=$this->baseurl.'question/'.$question['url'];?>&hashtags=HetVragenboekje,<?=str_replace(" & ", ",", $category['name']); foreach($tags as $tag) echo ",".$tag;?>&text=<?=(strlen($this->question['name']) > 20) ? substr($this->question['name'],0,20).'...' : $this->question['name'];?>" class="twitter-share">Tweet</a>
            </p>

        </div>

	    <div class="question-data">
		  
    	    <span class="date">Geplaatst op: <?php echo $date->toString("dd MMMM YYYY");?></span>
    	  
    	    <span class="answers"><img src="assets/img/comment.png"/><a class="magenta" href="question/<?= $question['url'] ?>"><?php echo $answers;?></a></span>
    	  
            <span class="user"><?php echo $user; ?></span>
		  
	    </div>

    </div>

    <div class="shadow-border">&nbsp;</div>

    <div class="tags">

        <?php foreach($tags as $tag) echo '<span><a href="tag/' . $tag . '">#' . $tag . '</a></span>'; ?>

    </div>

<?php endforeach; ?>

<div class="pagination">

    <ul>
        <?= @$this->pagination; ?>
    </ul>

</div>

<?php if( !count($this->questions) && $this->user['guide'] == 0 ): ?>
 
<!-- Modal -->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">

    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

    <h3 id="myModalLabel">Welkom op het vragenboekje.. Je kunt hier..</h3>

  </div>

<div class="modal-body">

    <h2>Een vraag stellen</h2>
    
    <p>
        Bereik heel Nederland. Stel je vraag online op Het Vragenboekje en alle andere gebruikers kunnen meteen antwoord geven. Je vraag wordt bovendien speciaal onder de aandacht gebracht bij mensen waarvan wij denken dat zij het antwoord weten.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/steleenvraag.png" />

    </div>

    <h2>Een vraag beantwoorden</h2>

    <p>
        Help anderen en geef antwoorden op recent gestelde vragen. Deel je kennis. Als je ingelogd bent vind je onderaan de vraag het
        beantwoord formulier.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/beantwoord.png" />

    </div>

    <h2>Je profiel bewerken</h2>
    
    <p>
        Bewerk jouw profiel met onder andere je eigen avatar! Deze komt voor bij het antwoorden van een vraag. Je kunt je profiel
        gemakkelijk aanpassen in het snelmenu.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/profielbewerken.png" />

    </div>

    <h2>Vragen printen op A5-formaat</h2>
    
    <p>
        Als ingelogd zijnde kun je vragen uitprinten op A5-formaat en deze opslaan in onze eigen speciale Vragenboekje A5-klapper.
        Klik op de knop "Print als PDF" om een PDF op maat te genereren! 
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/printpdf.png" />

    </div>

    <h2>Antwoorden liken (thumbsup)</h2>
    
    <p>
        Beoordeel antwoorden van anderen en geef deze een thumbsup om dit antwoord op de toppositie neer te zetten. Het antwoord
        met de meeste thumbsup zal in de print PDF worden meegenomen.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/thumbsup.png" />

    </div>

  </div>

  <div class="modal-footer">

    <button class="btn sluiten" style="float: right;" data-dismiss="modal" aria-hidden="true">Sluiten</button>

        <form action="questions" method="POST">

        <input type="hidden" name="guide" value="1" />
        <input type="submit" class="sluiten" style="margin: 2px 10px 0 0" name="submit" value="Melding niet meer weergeven" />

    </form>

  </div>

</div>

<link href="assets/css/modal.css" rel="stylesheet" type="text/css" />
<script src="assets/js/bootstrap-modal.js"></script>

<script type="text/javascript">

$(function() {
    $('#myModal').modal('toggle');
});

</script>

<?php endif; ?>