<?php
	$db = Zend_Registry::get('db');
?>

<h1 class="header">Vragen onder tag "<?php echo $this->tag; ?>"</h1>

<span id="email-error"class="hidden"><?=$this->error?></span>

<div class="shadow-border">&nbsp;</div>

<?php 
	
	foreach($this->questions as $question): 

    	$category = $db->fetchRow('SELECT name, url FROM categories WHERE id = ?', $question['category_id']);
    	$questioner = $db->fetchRow('SELECT * FROM users WHERE id = ?', $question['user_id']);
    	$answers = count( $db->fetchAll('SELECT * FROM answers WHERE question_id = ?', $question['id']) );
    	$date = new Zend_Date($question['date_created']);

    	($answers == 0 ? $answers = "Nog niet beantwoord." : $answers .= "x beantwoord");
	
		$cname = str_replace("&", "en", $category['name']);
		$sharelink = "https://www.facebook.com/dialog/feed?app_id=" . $this->appID . "&link=" . $this->baseurl . 'question/' . $question['url'] . "&picture=". $this->baseurl . "assets/img/fb.png&name=" . $question['name'] . "&caption=" . $cname . "&redirect_uri=" . $this->baseurl . 'question/' . $question['url'];

    ?>

		<div class="question">

		    <div class="question-image">
		    
		        <img src="assets/img/preview.png" />

		    </div>

		    <div class="question-info">

		        <a href="categorieen/<?= $category['url'] ?>" class="category"><?php echo $category['name']; ?></a>
		        
		        <p>
		            <a href="question/<?= $question['url'] ?>" class="title"><?php echo $question['name']; ?></a>
		            <a href="<?= $sharelink ?>" class="fb-share">Share</a>
				  <a href="https://twitter.com/share?url=<?=$this->baseurl.'question/'.$question['url'];?>&counturl=<?=$this->baseurl.'question/'.$question['url'];?>&hashtags=HetVragenboekje,<?=str_replace(" & ", ",", $category['name']); if($question['tags']){ echo ",".str_replace(";", ",", $question['tags']);}?>&text=<?=(strlen($question['name']) > 20) ? substr($question['name'],0,20).'...' : $question['name'];?>" class="twitter-share">Tweet</a>
		        </p>

		    </div>
		   
		   <div class="question-data">
			  
			  <span class="date">Geplaatst op: <?php echo $date->toString("dd MMMM YYYY");?></span>
			  
			  <span class="answers"><img src="assets/img/comment.png"/><?php echo $answers;?></span>

		      <span class="user"><?php echo $questioner['name']; ?></span>
			  
		   </div>

		</div>

		<div class="shadow-border">&nbsp;</div>

<?php 

	endforeach; 

?>