<h1 class="header">Vragen in de categorie <?php echo $this->category['name'] . ' (' . count( $this->questions ) . ')'; ?></h1>

<div class="shadow-border">&nbsp;</div>

	<?php 
		$db = Zend_Registry::get('db');

		if( $this->questions ):

			foreach($this->questions as $question): 

			$category = $db->fetchRow('SELECT name, url FROM categories WHERE id = ?', $question['category_id']);
			$answers = count( $db->fetchAll('SELECT * FROM answers WHERE question_id = ?', $question['id']) );
			$user = $db->fetchOne('SELECT name FROM users WHERE id = ?', $question['user_id']);
			$tags = explode(';', $question['tags']);
			
			$date = new Zend_Date($question['date_created']);
			
			($answers == 0 ? $answers = "Nog niet beantwoord." : $answers .= "x beantwoord");
			$cname = str_replace("&", "en", $category['name']);
			$sharelink = "https://www.facebook.com/dialog/feed?app_id=" . $this->appID . "&link=" . $this->baseurl . 'question/' . $question['url'] . "&picture=". $this->baseurl . "assets/img/fb.png&name=" . $question['name'] . "&caption=" . $cname . "&redirect_uri=" . $this->baseurl . 'question/' . $question['url'];
	?>

			<div class="question">

			    <div class="question-image">
			    
			        <img src="assets/img/categories/150x150/<?= $question['category_id'] ?>.png" />

			    </div>

			    <div class="question-info">

			        <a href="categorieen/<?= $this->category['url'] ?>" class="category"><?php echo $category['name']; ?></a>
			        
			        <p>
			            <a href="question/<?= $question['url'] ?>" class="title"><?php echo $question['name']; ?></a>
			            <a href="<?= $sharelink ?>" class="fb-share">Share</a>
            			<a href="https://twitter.com/share?url=<?=$this->baseurl.'question/'.$question['url'];?>&counturl=<?=$this->baseurl.'question/'.$question['url'];?>&hashtags=HetVragenboekje,<?=str_replace(" & ", ",", $category['name']); foreach($tags as $tag) echo ",".$tag;?>&text=Weet%20jij%20het%20antwoord%20op%20deze%20vraag?" class="twitter-share">Tweet</a>
			        </p>

			    </div>
			    
			    <div class="question-data">
		  
				<span class="date">Geplaatst op: <?php echo $date->toString("dd MMMM YYYY");?></span>

				<span class="answers"><img src="assets/img/comment.png"/><?php echo $answers;?></span>

				<span class="user"><?php echo $user; ?></span>

				</div>

			</div>

			<div class="shadow-border">&nbsp;</div>

			<div class="tags">

        		<?php foreach($tags as $tag) echo '<span><a href="tag/' . $tag . '">#' . $tag . '</a></span>'; ?>

   			</div>

	<?php 
			endforeach; 

		else:

		?>

			<p class="error">Geen vragen gevonden onder deze categorie !</p>

	<?php

		endif;
	?>