<h1 class="header">Vragen in de categorie <?php echo $this->category['name'] . ' (' . count( $this->questions ) . ')'; ?></h1>

<div class="shadow-border">&nbsp;</div>

	<?php 
		$db = Zend_Registry::get('db');

		if( $this->questions ):

			foreach($this->questions as $question): 

			$category = $db->fetchRow('SELECT name, url FROM categories WHERE id = ?', $question['category_id']);
			$answers = count( $db->fetchAll('SELECT * FROM answers WHERE question_id = ?', $question['id']) );
			$user = $db->fetchOne('SELECT name FROM users WHERE id = ?', $question['user_id']);
			$tags = explode(';', $question['tags']);
			
			$date = new Zend_Date($question['date_created']);
			
			($answers == 0 ? $answers = "Nog niet beantwoord." : $answers .= "x beantwoord");
	?>
		<!-- 

		// TO DO: VRAAG FIXEN VOLGENS NIEUW DESIGN

			<div class="question">

			    <a class="answers" href="question/<?php echo sanitize($question['name']); ?>"><?php echo (int) $answers ?></a>

			    <a id="category" href="categorieen/<?php echo $category['url']; ?>"><?php echo $category['name']; ?></a>

			    <span class="stars"><?php if($this->question_rating): echo $this->question_rating; else: echo '0'; endif; ?></span>

			    <a class="print" href="#">&nbsp;</a>

			    <a class="q" href="question/<?php echo sanitize($question['name']); ?>"><?php echo $question['name']; ?></a>

			    <span class="user"><a href="question/<?php echo sanitize($question['name']); ?>"><?php echo $user; ?></a> vraagt..</span>

			    <div class="tags">

			        <?php foreach($tags as $tag) echo '<span>' . $tag . '</span>'; ?>

			    </div>

			</div>

		-->

			<div class="question">

			    <div class="question-image">
			    
			        <img src="assets/img/preview.png" />

			    </div>

			    <div class="question-info">

			        <a href="categorieen/<?= $this->category['url'] ?>" class="category"><?php echo $category['name']; ?></a>
			        
			        <p>
			            <a href="question/<?= $this->question['url'] ?>" class="title"><?php echo $this->question['name']; ?></a>
			            <p class="title"><?php echo $question['name']; ?></p>
			        </p>

			    </div>
			    
			    <div class="question-data">
		  
				<span class="date">Geplaatst op: <?php echo $date->toString("dd MMMM YYYY");?></span>

				<span class="answers"><img src="assets/img/comment.png"/><?php echo $answers;?></span>

				</div>

			</div>

			<div class="shadow-border">&nbsp;</div>

			<div class="tags">

        		<?php foreach($tags as $tag) echo '<span>#' . $tag . '</span>'; ?>

   			</div>

	<?php 
			endforeach; 

		else:

		?>

			<p class="error">Geen vragen gevonden onder deze categorie !</p>

	<?php

		endif;
	?>