<h1 class="header">

   <span class="header-bg">Categorieën</span>

</h1>


<div class="shadow-border-3">&nbsp;</div>

<div id="categories">

	<?php 

	$i = 0;
	foreach( $this->categories as $category ):
	$i++;

	if( $i % 2 == 0 )
		$class = 'last';
	else $class = '';

	?>

	<a href="<?= $this->config->baseurl . $this->request->controller . '/' . $category['url']; ?>"> <div class="category <?= $class; ?>" id="c<?= $i; ?>">
		   
    <span class="name"><?php echo $category['name']; ?></span> 

    </div></a>

	<?php endforeach; ?>

</div>
