<h1 class="header">Categorieën</h1>

<div class="shadow-border">&nbsp;</div>

<div id="categories">

	<?php 

	$i = 0;
	foreach( $this->categories as $category ):
	$i++;

	if( $i % 2 == 0 )
		$class = 'last';
	else $class = '';

	?>

	<div class="category <?= $class; ?>" id="c<?= $i; ?>">

		<a href="<?= $this->config->baseurl . $this->request->controller . '/' . $category['url']; ?>" class="name"><?php echo $category['name']; ?></a> 

	</div>

	<?php endforeach; ?>

</div>
