<div class="categories">

	<h1>Categorieën (<?= count( $this->categories ); ?>)</h1>

	<?php 

	$i = 0;
	foreach( $this->categories as $category ):
	$i++;

	if( $i % 3 == 0 )
		$class = 'last';
	else $class = '';

	echo '
	<div class="category ' . $class . '" style="background: url("assets/img/categories/'.$i.'.png") no-repeat;">

		<a href="' . $this->config->baseurl . $this->request->controller . '/' . $category['url'] . '" class="name">' . $category['name'] . '</a> 

		<div class="category-question">
	
			<a href="#" class="cat-q">Mijn headset is kapot gegaan alleen hoe krijg ik de garantie? Ik hem bij de e-plaza gekocht en die is failliet.</a>
			<a href="#answers" class="cat-a">4 antwoorden</a>

		</div>

	</div>';

	endforeach;

	?>

</div>
