<h1 class="header">Stel een vraag</h1>

<span style="color: red;"><?= $this->steleenvraag_error ?></span>

<div class="shadow-border">&nbsp;</div>

<div id="formulier" class="steleenvraagform">

	<div class="formulier-top">&nbsp;</div>

	<div class="stel-een-vraag-image">&nbsp;</div>

	<form id="steleenvraag" action="steleenvraag" method="POST">

		<fieldset>

			<label>* Categorie:</label>
			<?php echo $this->form->getElement('category_id'); ?>

			<label for="tags">Tags (gescheiden door ;)</label>
			<?php echo $this->form->getElement('tags'); ?>

			<label for="vraag">* Stel je vraag:</label>
			<?php echo $this->form->getElement('name'); ?><br /><br />

			<input type="submit" class="submit" value="Vraag stellen" />

		</fieldset>

	</form>

	<div class="errors"></div>

</div>

<script type="text/javascript">

var value = $("#category_id");
var image = $(".stel-een-vraag-image");

value.on("change", function() {
	var option = $("#category_id option:selected").val();
	image.css("background", "url(assets/img/categories/150x150/" + option + ".png)");
});

</script>
