<?php
$this->layout()->title = $this->translate('Categorieen overzicht');
$db = Zend_Registry::get('db');
?>
<section class=categories>
    <table>
        <thead>
            <tr>
                <th width="1200"><?php echo $this->translate('Categorie');?>
                <th>Wijzig
                <th>Verwijder
        </thead>
        <tbody>
            <?php 
            $items = $this->items;
            foreach($items as $i => $item):
            ?>
            <tr>
                <td><?php echo $item['name']; ?></td>
                <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id'])) ?>"><?php echo $this->translate('Wijzig');?></a></td>
                <td class=delete><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id'])) ?>"><?php echo $this->translate('Verwijder');?></a></td>
            </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</section>