<h1 class="header">

   <span class="header-bg">Wachtwoord vergeten</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>

<form action="wachtwoord-vergeten" method="POST">

	<fieldset>

		<label for="email">Geef e-mail op om een nieuw wachtwoord te versturen</label><br /><br />
		<input type="email" name="email" id="email" style="padding: 10px; width: 350px;" placeholder="E-mail" /><br /><br />

		<input type="submit" class="submit" name="submit" style="float: left;" value="Haal nieuw wachtwoord op" />

	</fieldset>

</form>