<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <title>Het Vragenboekje - Wachtwoord Vergeten</title>
   <style type="text/css">
   	a {color: #4A72AF;}
	body, #header h1, #header h2, p {margin: 0; padding: 0;}
	#main {border: 1px solid #cfcece;}
	img {display: block;}
	#top-message p, #bottom-message p {color: #3f4042; font-size: 12px; font-family: Arial, Helvetica, sans-serif; }
	#header h1 {color: #ffffff !important; font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", sans-serif; font-size: 24px; margin-bottom: 0!important; padding-bottom: 0; }
	#header h2 {color: #ffffff !important; font-family: Arial, Helvetica, sans-serif; font-size: 24px; margin-bottom: 0 !important; padding-bottom: 0; }
	#header p {color: #ffffff !important; font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", sans-serif; font-size: 12px;  }
	h1, h2, h3, h4, h5, h6 {margin: 0 0 0.8em 0;}
	h3 {font-size: 28px; color: #444444 !important; font-family: Arial, Helvetica, sans-serif; }
	h4 {font-size: 22px; color: #4A72AF !important; font-family: Arial, Helvetica, sans-serif; }
	h5 {font-size: 18px; color: #444444 !important; font-family: Arial, Helvetica, sans-serif; }
	p {font-size: 12px; color: #444444 !important; font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", sans-serif; line-height: 1.5;}
   </style>
</head>

<body>
<table width="100%" cellpadding="50" cellspacing="0" bgcolor="e4e4e4"><tr><td>

	<table id="main" style="background: url('assets/img/body-bg.png') repeat-x #fff;" width="650" align="center" cellpadding="0" cellspacing="15" bgcolor="ffffff">
		<tr>
			<td>
				<table id="header" cellpadding="10" cellspacing="0" align="center" bgcolor="000000">
					<tr>
						<td width="638" height="110" style="padding: 10px 0 0 0; background: url('assets/img/logo.png') no-repeat center;"></td>
					</tr>
				</table><!-- header -->
			</td>
		</tr><!-- header -->
		
		<tr>
			<td>
				<table id="content-2" cellpadding="0" cellspacing="0" border="0" align="center">
					<tr>
						<td width="638" style="background: url('assets/img/navigation.png');" border="0"><p style="font-weight: bold; padding: 10px 0; font-size: 14px; color: #fff !important; text-align: center; ">Wachtwoord Vergeten</p></td>
					</tr>
					<tr>
						<td width="638" height="9" style="background: url('assets/img/shadow570.png') no-repeat left;"></td>
					</tr>
				</table><!-- content-2 -->
			</td>
		</tr>

		<tr>
			<td align="center">
				<p style="font-size: 16px; margin: 0 0 20px 0;">Je bent je wachtwoord vergeten. Klik op de volgende link om een nieuw wachtwoord in te voeren.</p>
				<a href="<?= $this->link ?>" style="font-size: 14px; font-family: arial; font-weight: bold; text-decoration: none; background: url('assets/img/navigation.png'); padding: 5px 8px; color: #fff;">Vraag nieuw wachtwoord aan</a>
			</td>
		</tr>
		
	</table><!-- main -->
</td></tr></table><!-- wrapper -->

</body>
</html>