<link rel="stylesheet" type="text/css" href="assets/css/uploadify.css" />

<h1 class="header">Pas je profiel aan</h1>

<div class="shadow-border">&nbsp;</div>

<div id="formulier">

	<form enctype="multipart/form-data" action="profiel" method="POST">

		<fieldset>

			<div class="preview">

				<?php if( $this->user['image'] ): ?>

					<img id="thumb" width="150" height="150" src="uploads/images/<?= $this->user['image'] ?>" />

				<?php else: ?>

					<img id="thumb" width="150" height="150" src="assets/img/profile_unknown.png" />

				<?php endif; ?>

			</div>

			<input type="file" name="file" id="file_upload" >

			<label for="name">* Naam:</label>
			<?php echo $this->form->getElement('name'); ?><br />

			<label for="lastname">Achternaam:</label>
			<?php echo $this->form->getElement('lastname'); ?><br />

			<label for="email">Email</label>
			<?php echo $this->form->getElement('email'); ?><br /><br />

			<input type="submit" class="submit" value="Aanpassen" />

		</fieldset>

	</form>

</div>

<script type="text/javascript" src="assets/js/jquery.uploadify.min.js"></script>
<script type="text/javascript">

$(function() {
    $('#file_upload').uploadify({
    	'buttonText' : 'Upload Profielfoto',
    	'swf'      : 'assets/swf/uploadify.swf',
    	'checkExisting' : 'check-exists',
        'uploader' : 'photo',
        'queueSizeLimit' : 1,
        'uploadLimit' : 1,
        'fileSizeLimit' : '150KB',
        'onUploadSuccess' : function(file, data, response) {
            alert('De  foto' + file.name + ' is succesvol geupload');
            $("#thumb").attr("src", "uploads/images/" + file.name);
        }
    });
});

</script>