<h1 class="header">Pas je profiel aan</h1>

<div class="shadow-border">&nbsp;</div>

<div id="formulier">

	<form action="profiel" method="POST">

		<fieldset>

			<label for="name">* Naam:</label>
			<?php echo $this->form->getElement('name'); ?><br />

			<label for="lastname">Achternaam:</label>
			<?php echo $this->form->getElement('lastname'); ?><br />

			<label for="email">Email</label>
			<?php echo $this->form->getElement('email'); ?><br /><br />

			<input type="submit" class="submit" value="Aanpassen" />

		</fieldset>

	</form>

</div>
