<h1 class="header">

   <span class="header-bg">Wachtwoord vergeten</span>

</h1>

<div class="shadow-border-3">&nbsp;</div>

<form action="wachtwoord-vergeten" id="wachtwoordvergeten" method="POST">

	<fieldset>

		<label for="email">Geef e-mail op</label>
		<input type="email" id="email" placeholder="E-mail" /><br />

		<input type="submit" class="submit" style="float: left;" value="Haal nieuw wachtwoord op" />

	</fieldset>

</form>