<!-- Modal -->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">

    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

    <h3 id="myModalLabel">Welkom op het vragenboekje.. Je kunt hier..</h3>

  </div>

  <div class="modal-body">

    <h2>Een vraag stellen</h2>
    
    <p>
        Bereik heel Nederland. Stel je vraag online op Het Vragenboekje en alle andere gebruikers kunnen meteen antwoord geven. Je vraag wordt bovendien speciaal onder de aandacht gebracht bij mensen waarvan wij denken dat zij het antwoord weten.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/steleenvraag.png" />

    </div>

    <h2>Een vraag beantwoorden</h2>

    <p>
        Help anderen en geef antwoorden op recent gestelde vragen. Deel je kennis. Als je ingelogd bent vind je onderaan de vraag het
        beantwoord formulier.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/beantwoord.png" />

    </div>

    <h2>Je profiel bewerken</h2>
    
    <p>
        Bewerk jouw profiel met onder andere je eigen avatar! Deze komt voor bij het antwoorden van een vraag. Je kunt je profiel
        gemakkelijk aanpassen in het snelmenu.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/profielbewerken.png" />

    </div>

    <h2>Vragen printen op A5-formaat</h2>
    
    <p>
        Als ingelogd zijnde kun je vragen uitprinten op A5-formaat en deze opslaan in onze eigen speciale Vragenboekje A5-klapper.
        Klik op de knop "Print als PDF" om een PDF op maat te genereren! 
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/printpdf.png" />

    </div>

    <h2>Antwoorden liken (thumbsup)</h2>
    
    <p>
        Beoordeel antwoorden van anderen en geef deze een thumbsup om dit antwoord op de toppositie neer te zetten. Het antwoord
        met de meeste thumbsup zal in de print PDF worden meegenomen.
    </p>

    <div class="modal-image">

        <img src="assets/img/guide/thumbsup.png" />

    </div>

  </div>

  <div class="modal-footer">

    <button class="btn sluiten" style="float: right;" data-dismiss="modal" aria-hidden="true">Sluiten</button>

  </div>

</div>

<link href="assets/css/modal.css" rel="stylesheet" type="text/css" />
<script src="assets/js/bootstrap-modal.js"></script>

<script type="text/javascript">

$(function() {
    $('#myModal').modal('toggle');
});

</script>